# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf input

# version format
version: "AppVeyor build {build}"

environment:
  # The codeclimate-test-reporter expects an env. variable with this name.
  CODECLIMATE_REPO_TOKEN: eafd204769d6f461a5835536441a1e78a1db4dd10658fd213398123fedece7eb
  matrix:
    - nodejs_version: 0.10

build: off

test_script:
  - node --version
  - npm --version
  - npm install
  - npm test
  - node_modules/.bin/codeclimate < coverage/lcov.info
